### ISSUE TITLE
When translating some mail templates, a "No Subject was found for %s in the database." error raises. Translation impossible

### ISSUE THREAD

**Issue by DaoKakao** [thirtybees/mailalerts#3]
This caused by the weird structure of mailalerts module: it has mail template's subjects hardcoded in the php file. Then translation system retrieves this subjects from .php file with parsing subroutine, which leads to failure at the lines ##1251-1254 of the mailalerts.php file:
```
            Mail::l(
                'Your order has been changed',
                (int) $order->id_lang
            ),
```
If we remove line feeds, unwrapping 4 lines of code into one, then error disappears.

**Comment by getdatakick** [comment]
This issue is closed by 5f65b70
